# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Front

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./front


    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: npm run build --if-present
    - name: Create SSH
      run: mkdir ~/.ssh
    - name: Install SSH Key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    - name: Setup Perm
      run: chmod 600 ~/.ssh/id_rsa
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -avz -e 'ssh -i ~/.ssh/id_rsa' ./build/ ls1@${{ secrets.SSH_HOST }}:/home/github/build/

    # serve:

    #   runs-on: ubuntu-latest

    #   steps:
